layer_dir_map = {
    0: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp0/layers.0.mlp",
    1: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp1/layers.1.mlp",
    2: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp2/layers.2.mlp",
    3: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp3/layers.3.mlp",
    4: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp4/layers.4.mlp",
    5: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp5/layers.5.mlp",
    6: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp6/layers.6.mlp",
    7: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp7/layers.7.mlp",
    8: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp8/layers.8.mlp",
    9: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp9/layers.9.mlp",
    10: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp10/layers.10.mlp",
    11: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp11/layers.11.mlp",
    12: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp12/layers.12.mlp",
    13: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp13/layers.13.mlp",
    14: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp14/layers.14.mlp",
    15: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp15/layers.15.mlp",
    16: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp16/layers.16.mlp",
    17: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp17/layers.17.mlp",
    18: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp18/layers.18.mlp",
    19: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp19/layers.19.mlp",
    20: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp20/layers.20.mlp",
    21: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp21/layers.21.mlp",
    22: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp22/layers.22.mlp",
    23: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp23/layers.23.mlp",
    24: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp24/layers.24.mlp",
    25: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp25/layers.25.mlp",
    26: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp26/layers.26.mlp",
    27: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp27/layers.27.mlp",
    28: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp28/layers.28.mlp",
    29: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp29/layers.29.mlp",
    30: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp30/layers.30.mlp",
    31: "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/remote/sparsify/checkpoints/llama3/sparsify_llada8b_latents32768_bs256_mlp31/layers.31.mlp",
}

model_map = {
    "Llama-3-8B": "/home/notebook/code/group/xuekaiwen/mask_diffusion/interpretable_models/data/meta-llama/Meta-Llama-3-8B"
}
